name: alasight
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.10,<3.13   
  - numpy
  - six
  - skani>=0.3.2
  - pandas
  - matplotlib
  - pip
  - pip:
      - ete3
      - pydustmasker
